export interface PageTemplate {
  id: string;
  nameKey: string;
  descriptionKey: string;
  icon: string;
  content: string;
}

export const builtInTemplates: PageTemplate[] = [
  {
    id: 'blank',
    nameKey: 'templates.blank',
    descriptionKey: 'templates.blankDesc',
    icon: '📄',
    content: '',
  },
  {
    id: 'meeting',
    nameKey: 'templates.meeting',
    descriptionKey: 'templates.meetingDesc',
    icon: '🤝',
    content: [
      '## Meeting Notes',
      '',
      '**Date:** YYYY-MM-DD',
      '**Attendees:**',
      '',
      '- [ ] Name 1',
      '- [ ] Name 2',
      '- [ ] Name 3',
      '',
      '---',
      '',
      '## Agenda',
      '',
      '1. Topic 1',
      '2. Topic 2',
      '3. Topic 3',
      '',
      '## Discussion',
      '',
      '### Topic 1',
      '',
      '',
      '',
      '### Topic 2',
      '',
      '',
      '',
      '## Action Items',
      '',
      '- [ ] Action item 1 — @owner, due YYYY-MM-DD',
      '- [ ] Action item 2 — @owner, due YYYY-MM-DD',
      '- [ ] Action item 3 — @owner, due YYYY-MM-DD',
      '',
    ].join('\n'),
  },
  {
    id: 'decision',
    nameKey: 'templates.decision',
    descriptionKey: 'templates.decisionDesc',
    icon: '⚖️',
    content: [
      '## Decision Log',
      '',
      '| Field | Value |',
      '|-------|-------|',
      '| **Status** | Proposed / Accepted / Rejected |',
      '| **Date** | YYYY-MM-DD |',
      '| **Stakeholders** | Name 1, Name 2 |',
      '',
      '---',
      '',
      '## Background',
      '',
      'Describe the context and problem that requires a decision.',
      '',
      '## Options',
      '',
      '### Option A',
      '',
      '- **Pros:** ...',
      '- **Cons:** ...',
      '',
      '### Option B',
      '',
      '- **Pros:** ...',
      '- **Cons:** ...',
      '',
      '### Option C',
      '',
      '- **Pros:** ...',
      '- **Cons:** ...',
      '',
      '## Decision',
      '',
      'State the chosen option.',
      '',
      '## Rationale',
      '',
      'Explain why this option was selected over the alternatives.',
      '',
    ].join('\n'),
  },
  {
    id: 'retrospective',
    nameKey: 'templates.retrospective',
    descriptionKey: 'templates.retrospectiveDesc',
    icon: '🔄',
    content: [
      '## Retrospective',
      '',
      '**Sprint / Period:** ',
      '**Date:** YYYY-MM-DD',
      '',
      '---',
      '',
      '## What Went Well',
      '',
      '- ',
      '- ',
      '- ',
      '',
      '## What Didn\'t Go Well',
      '',
      '- ',
      '- ',
      '- ',
      '',
      '## Action Items',
      '',
      '- [ ] Action item 1 — @owner',
      '- [ ] Action item 2 — @owner',
      '- [ ] Action item 3 — @owner',
      '',
    ].join('\n'),
  },
  {
    id: 'projectPlan',
    nameKey: 'templates.projectPlan',
    descriptionKey: 'templates.projectPlanDesc',
    icon: '📋',
    content: [
      '## Project Plan',
      '',
      '### Overview',
      '',
      'Brief description of the project.',
      '',
      '### Goals',
      '',
      '- Goal 1',
      '- Goal 2',
      '- Goal 3',
      '',
      '### Timeline',
      '',
      '| Phase | Start | End | Status |',
      '|-------|-------|-----|--------|',
      '| Phase 1 | YYYY-MM-DD | YYYY-MM-DD | Not Started |',
      '| Phase 2 | YYYY-MM-DD | YYYY-MM-DD | Not Started |',
      '| Phase 3 | YYYY-MM-DD | YYYY-MM-DD | Not Started |',
      '',
      '### Milestones',
      '',
      '- [ ] Milestone 1 — YYYY-MM-DD',
      '- [ ] Milestone 2 — YYYY-MM-DD',
      '- [ ] Milestone 3 — YYYY-MM-DD',
      '',
      '### Risks',
      '',
      '| Risk | Impact | Likelihood | Mitigation |',
      '|------|--------|------------|------------|',
      '| Risk 1 | High | Medium | ... |',
      '| Risk 2 | Medium | Low | ... |',
      '',
    ].join('\n'),
  },
  {
    id: 'howto',
    nameKey: 'templates.howto',
    descriptionKey: 'templates.howtoDesc',
    icon: '📖',
    content: [
      '## How-To Guide',
      '',
      '### Overview',
      '',
      'What this guide covers and who it is for.',
      '',
      '### Prerequisites',
      '',
      '- Prerequisite 1',
      '- Prerequisite 2',
      '- Prerequisite 3',
      '',
      '### Steps',
      '',
      '1. **Step 1** — Description of the first step.',
      '',
      '2. **Step 2** — Description of the second step.',
      '',
      '3. **Step 3** — Description of the third step.',
      '',
      '4. **Step 4** — Description of the fourth step.',
      '',
      '### Troubleshooting',
      '',
      '**Problem:** Description of a common issue.',
      '',
      '**Solution:** How to fix it.',
      '',
      '---',
      '',
      '**Problem:** Another common issue.',
      '',
      '**Solution:** How to fix it.',
      '',
    ].join('\n'),
  },
  {
    id: 'changelog',
    nameKey: 'templates.changelog',
    descriptionKey: 'templates.changelogDesc',
    icon: '📝',
    content: [
      '## Changelog',
      '',
      '### v1.0.0 — YYYY-MM-DD',
      '',
      '#### Added',
      '',
      '- New feature 1',
      '- New feature 2',
      '',
      '#### Changed',
      '',
      '- Changed behavior 1',
      '- Changed behavior 2',
      '',
      '#### Fixed',
      '',
      '- Bug fix 1',
      '- Bug fix 2',
      '',
      '---',
      '',
      '### v0.1.0 — YYYY-MM-DD',
      '',
      '#### Added',
      '',
      '- Initial release',
      '',
    ].join('\n'),
  },
];
